apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitriver-live.fullname" . }}-transcoder-public
  labels:
    {{- include "bitriver-live.labels" . | nindent 4 }}
data:
  nginx.conf: |-
{{ .Files.Get "files/transcoder-public.conf" | indent 4 }}
