apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitriver-live.fullname" . }}-srs-conf
  labels:
    {{- include "bitriver-live.labels" . | nindent 4 }}
data:
  srs.conf: |-
{{ .Files.Get "files/srs.conf" | indent 4 }}
