apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitriver-live.fullname" . }}-secrets
  labels:
    {{- include "bitriver-live.labels" . | nindent 4 }}
type: Opaque
stringData:
  BITRIVER_LIVE_ADMIN_EMAIL: {{ .Values.secrets.BITRIVER_LIVE_ADMIN_EMAIL | quote }}
  BITRIVER_LIVE_ADMIN_PASSWORD: {{ .Values.secrets.BITRIVER_LIVE_ADMIN_PASSWORD | quote }}
  BITRIVER_SRS_TOKEN: {{ .Values.secrets.BITRIVER_SRS_TOKEN | quote }}
  BITRIVER_OME_USERNAME: {{ .Values.secrets.BITRIVER_OME_USERNAME | quote }}
  BITRIVER_OME_PASSWORD: {{ .Values.secrets.BITRIVER_OME_PASSWORD | quote }}
  BITRIVER_OME_API_TOKEN: {{ .Values.secrets.BITRIVER_OME_API_TOKEN | quote }}
  BITRIVER_OME_ACCESS_TOKEN: {{ .Values.secrets.BITRIVER_OME_ACCESS_TOKEN | quote }}
  BITRIVER_TRANSCODER_TOKEN: {{ .Values.secrets.BITRIVER_TRANSCODER_TOKEN | quote }}
  BITRIVER_REDIS_PASSWORD: {{ .Values.secrets.BITRIVER_REDIS_PASSWORD | quote }}
  BITRIVER_LIVE_CHAT_QUEUE_REDIS_PASSWORD: {{ .Values.secrets.BITRIVER_LIVE_CHAT_QUEUE_REDIS_PASSWORD | quote }}
  BITRIVER_POSTGRES_USER: {{ .Values.secrets.BITRIVER_POSTGRES_USER | quote }}
  BITRIVER_POSTGRES_PASSWORD: {{ .Values.secrets.BITRIVER_POSTGRES_PASSWORD | quote }}
  BITRIVER_LIVE_METRICS_TOKEN: {{ .Values.secrets.BITRIVER_LIVE_METRICS_TOKEN | quote }}
  BITRIVER_LIVE_RATE_LOGIN_LIMIT: {{ .Values.secrets.BITRIVER_LIVE_RATE_LOGIN_LIMIT | quote }}
  BITRIVER_LIVE_RATE_LOGIN_WINDOW: {{ .Values.secrets.BITRIVER_LIVE_RATE_LOGIN_WINDOW | quote }}
  BITRIVER_LIVE_POSTGRES_DSN: {{ include "bitriver-live.postgresDsn" . | quote }}
