#!/usr/bin/env bash
set -euo pipefail

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Error: $1 is required but was not found in PATH." >&2
    return 1
  fi
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
COMPOSE_FILE="$REPO_ROOT/deploy/docker-compose.yml"

require_command docker || exit 1

if ! docker compose version >/dev/null 2>&1; then
  echo "Error: Docker Compose V2 is required. Install the docker compose plugin for Docker and try again." >&2
  exit 1
fi

echo "Docker and Docker Compose detected."

if [ -f "$ENV_FILE" ]; then
  echo "Existing .env file detected at $ENV_FILE. Skipping regeneration."
else
  {
    printf '# Generated by scripts/quickstart.sh on %s\n' "$(date -u +'%%Y-%%m-%%dT%%H:%%M:%%SZ')"
    echo "# Update the admin email, password, and viewer URL before inviting real users."
    cat <<'EOF'
BITRIVER_INGEST_HEALTH=/healthz
BITRIVER_LIVE_ADDR=:8080
BITRIVER_LIVE_ADMIN_EMAIL=admin@example.com
BITRIVER_LIVE_ADMIN_PASSWORD=change-me-now
BITRIVER_LIVE_MODE=production
BITRIVER_LIVE_PORT=8080
BITRIVER_LIVE_POSTGRES_ACQUIRE_TIMEOUT=5s
BITRIVER_LIVE_POSTGRES_DSN=postgres://bitriver:bitriver@postgres:5432/bitriver?sslmode=disable
BITRIVER_LIVE_POSTGRES_MAX_CONN_LIFETIME=30m
BITRIVER_LIVE_POSTGRES_MAX_CONNS=15
BITRIVER_LIVE_POSTGRES_MIN_CONNS=5
BITRIVER_LIVE_STORAGE_DRIVER=postgres
BITRIVER_OME_API=http://ome:8081
BITRIVER_OME_HTTP_PORT=8081
BITRIVER_OME_PASSWORD=local-dev-password
BITRIVER_OME_SIGNALLING_PORT=9000
BITRIVER_OME_USERNAME=admin
BITRIVER_POSTGRES_PORT=5432
BITRIVER_REDIS_PORT=6379
BITRIVER_SRS_API=http://srs:1985
BITRIVER_SRS_API_PORT=1985
BITRIVER_SRS_RTMP_PORT=1935
BITRIVER_SRS_TOKEN=local-dev-token
BITRIVER_TRANSCODER_API=http://transcoder:9000
BITRIVER_TRANSCODER_HOST_PORT=9001
BITRIVER_TRANSCODER_TOKEN=local-dev-token
BITRIVER_VIEWER_ORIGIN=http://viewer:3000
NEXT_PUBLIC_API_BASE_URL=
NEXT_PUBLIC_VIEWER_URL=http://localhost:8080/viewer
NEXT_VIEWER_BASE_PATH=/viewer
EOF
  } > "$ENV_FILE"
  echo "Wrote default environment configuration to $ENV_FILE."
fi

cd "$REPO_ROOT"
export COMPOSE_FILE="$COMPOSE_FILE"

echo "Starting BitRiver Live stack..."
docker compose up -d

echo "Stack is starting. Use 'docker compose logs -f' to follow service output."
